name: Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ format(github.event.pull_request.head.ref, '/', '_') }}-*

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          tag: latest
